### ISSUE TITLE
Debug production

### ISSUE THREAD

**Issue by JulienRaad** [JakeWharton/ProcessPhoenix#28]
Hello Android God

Is this library for debug or production ? 

For example, can I use it for killing the app process when a use changes the app language ? 

I notice this line of code in the onCreate of the application class
if (ProcessPhoenix.isPhoenixProcess(this)) {
            return;
        }

Thank you

**Comment by crgarridos** [comment]
I don't know about the conflict that the lib could be lead. But as the readme states: 

> This should only be used for things like fundamental state changes in your debug builds (e.g., changing from staging to production).

**Comment by JakeWharton** [comment]
Your app should restart automatically when the user changes the device language because that is a configuration change. If you have an application-level language selector rather than relying on the system language you can trigger the activity to restart with `recreate()`. That doesn't help for multi-activity apps though. Nothing explicitly prevents you from using this library in production though.
